---
title: "Model fitting"
author: Zhang and Sheng
date: "Updated at `r lubridate::now()`"
output:
  html_notebook:
    theme: readable
    toc: true
    number_section: true
---

```{r load packages and configurations, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# load packages
library(tidyverse)
library(stringr)
library(psych)
library(extrafont)
# configurations ----
filt_dir <- "EFFiltered"
sublist <- parse_integer(read_lines(file.path(filt_dir, "sublist.txt")))
cfa_dir <- "cfa"
data_dir <- file.path(cfa_dir, "data")
img_dir <- file.path(cfa_dir, "image")
```

```{r load data and filter out not used subjects, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
ef_data_raw <- read_csv(file.path(filt_dir, "ef_behav_all.csv")) %>%
  filter(id %in% sublist) %>%
  select(-id)
```

```{r data transformation in order that high score -> high ability, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
ef_data_tran <- ef_data_raw %>%
  mutate(
    # logit transformation to stabilize
    AntiSac = logit(1 - AntiSac),
    CateSwitch = - CateSwitch,
    # due to the small sample size, use Bayesian estimation
    # PC = (n + 1) / (N + 2)
    KeepTrack = logit((KeepTrack + 1) / 38),
    ShiftColor = - ShiftColor,
    ShiftNumber = - ShiftNumber,
    StopSignal = - StopSignal,
    Stroop = - Stroop
  )
```

```{r indices standardisation and store standardized data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
ef_data_tran_scale <- ef_data_tran %>%
  mutate_all(scale) %>%
  select(AntiSac, StopSignal, Stroop,
         CateSwitch, ShiftColor, ShiftNumber,
         KeepTrack, spatialWM, WM3)
write_csv(ef_data_tran_scale, file.path(data_dir, "EF.csv"))
```

```{r descriptive statistics, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
describe(ef_data_tran_scale)
```

```{r visualisation of raw data, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
ef_data_raw_stack <- gather(ef_data_raw, task, score) %>%
  mutate(
    task = factor(
      task,
      levels = c(
        "AntiSac", "StopSignal", "Stroop",
        "CateSwitch", "ShiftColor", "ShiftNumber",
        "KeepTrack", "spatialWM", "WM3")
    )
  )
ggplot(ef_data_raw_stack, aes(score, fill = task)) +
  geom_histogram() +
  facet_wrap(~ task, scales = "free") +
  labs(title = "Distribution of raw scores") +
  theme_minimal() +
  theme(
    plot.title = element_text(family = "Gill Sans MT", size = 20, hjust = 0.5, margin = margin(b = 20)),
    axis.title = element_text(family = "Gill Sans MT", size = 16),
    axis.text = element_text(family = "Gill Sans MT", size = 12),
    legend.text = element_text(family = "Gill Sans MT", size = 12),
    strip.text = element_text(family = "Gill Sans MT", size = 16),
    legend.title = element_text(family = "Gill Sans MT", size = 16),
    plot.margin = margin(20, 20, 20, 20)
  )
ggsave(file.path(img_dir, "Distribution Raw Data.jpg"))
```

```{r visualisation transformed data, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
ef_data_tran_stack <- gather(ef_data_tran, task, score) %>%
  mutate(
    task = factor(
      task,
      levels = c(
        "AntiSac", "StopSignal", "Stroop",
        "CateSwitch", "ShiftColor", "ShiftNumber",
        "KeepTrack", "spatialWM", "WM3")
    )
  )
ggplot(ef_data_tran_stack, aes(score, fill = task)) +
  geom_histogram() +
  facet_wrap(~ task, scales = "free") +
  labs(title = "Distribution of transformed scores") +
  theme_minimal() +
  theme(
    plot.title = element_text(family = "Gill Sans MT", size = 20, hjust = 0.5, margin = margin(b = 20)),
    axis.title = element_text(family = "Gill Sans MT", size = 16),
    axis.text = element_text(family = "Gill Sans MT", size = 12),
    legend.text = element_text(family = "Gill Sans MT", size = 12),
    strip.text = element_text(family = "Gill Sans MT", size = 16),
    legend.title = element_text(family = "Gill Sans MT", size = 16),
    plot.margin = margin(20, 20, 20, 20)
  )
ggsave(file.path(img_dir, "Distribution Transformed Data.jpg"))
```

```{r visualisation scaled data in Q-Q plot, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
ef_data_scale_stack <- gather(ef_data_tran_scale, task, score) %>%
  mutate(
    task = factor(
      task,
      levels = c(
        "AntiSac", "StopSignal", "Stroop",
        "CateSwitch", "ShiftColor", "ShiftNumber",
        "KeepTrack", "spatialWM", "WM3")
      )
    )
ggplot(ef_data_scale_stack, aes(sample = score, color = task)) +
  stat_qq() +
  geom_abline(slope = 1, intercept = 0, alpha = 0.5, linetype = "dashed") +
  facet_wrap(~ task) +
  labs(title = "Q-Q plot of all tasks") +
  theme_minimal() +
  theme(
    plot.title = element_text(family = "Gill Sans MT", size = 20, hjust = 0.5, margin = margin(b = 20)),
    axis.title = element_text(family = "Gill Sans MT", size = 16),
    axis.text = element_text(family = "Gill Sans MT", size = 12),
    legend.text = element_text(family = "Gill Sans MT", size = 12),
    strip.text = element_text(family = "Gill Sans MT", size = 16),
    legend.title = element_text(family = "Gill Sans MT", size = 16),
    plot.margin = margin(20, 20, 20, 20)
    )
ggsave(file.path(img_dir, "Q-Q plot.jpg"))
```

```{r multinormal test, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
mardia(ef_data_tran_scale)
```
